pipeline:
  name: Build AngularWithAzure
  identifier: Build_AngularWithAzure_1762188769213
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        template:
          templateRef: AngularBuildTemplate
          versionLabel: v1
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        repoName: AngularWithAzure
        build: <+input>
